### PR TITLE
Change percent bootstrap size

### PR DESCRIPTION
**Pull request by jdramsey**
Changing form 90 to 100

### CODE REVIEW

**Comment by jdramsey** [comment]
https://github.com/cmu-phil/tetrad/issues/1552

**Review by kvb2univpitt — COMMENTED** [review]
I am confused about this pull request.  I see the changes to the project version number in POM files, but I don't see any changes related to **_percent bootstrap size_**.  Am I missing something?

**Comment by jdramsey** [comment]
The version numbers were the last snapshot I made for Clark; I'll change those. But in 

https://github.com/cmu-phil/tetrad/blob/bootstrapPercentChange/docs/manual/index.html

line 7484, percentDiscrete should be set to 100; int he interface if you build it this is the case, no?

**Comment by jdramsey** [comment]
Sorry, line 7502

            <li>Default Value: <span
                    id="percentResampleSize_default_value">100</span></li>
            <li>Lower

**Comment by kvb2univpitt** [comment]
@jdramsey Ok.  Now I see the file with the change.

**Review by kvb2univpitt — APPROVED** [review]
Looks good!

**Pull request merged**
