### PR TITLE
New rest client

### PR DESCRIPTION
**Pull request by chirayukong**

### CODE REVIEW

**Comment by yuanzhou** [comment]
@chirayukong I got this build error, can you resolve the dependency error?

capture

**Comment by yuanzhou** [comment]
I tested and right after I chose to run a GFCI search on AWS, it pops this screen with the following exception message:

capture
 
````
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at javax.swing.plaf.basic.BasicTextUI.getVisibleEditorRect(BasicTextUI.java:995)
	at javax.swing.plaf.basic.BasicTextUI.paintSafely(BasicTextUI.java:735)
	at javax.swing.plaf.basic.BasicTextUI.paint(BasicTextUI.java:881)
	at javax.swing.plaf.basic.BasicTextUI.update(BasicTextUI.java:860)
	at javax.swing.JComponent.paintComponent(JComponent.java:780)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:290)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at javax.swing.plaf.basic.BasicTextUI.getVisibleEditorRect(BasicTextUI.java:995)
	at javax.swing.plaf.basic.BasicTextUI.paintSafely(BasicTextUI.java:735)
	at javax.swing.plaf.basic.BasicTextUI.paint(BasicTextUI.java:881)
	at javax.swing.plaf.basic.BasicTextUI.update(BasicTextUI.java:860)
	at javax.swing.JComponent.paintComponent(JComponent.java:780)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:290)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)08:21:02.979 [Thread-11] INFO edu.cmu.tetradapp.editor.GeneralAlgorithmEditor - /tmp/Tetrad-data-4953854784816802245.txt

	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
08:21:02.979 [Thread-11] INFO edu.cmu.tetradapp.editor.GeneralAlgorithmEditor - parameter: alpha	value: 0.01
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)08:21:02.979 [Thread-11] INFO edu.cmu.tetradapp.editor.GeneralAlgorithmEditor - parameter: penaltyDiscount	value: 2.0
````

If I just ignore this and click OK button, I still see the parameters screen instead of the generated graph. And a DB error:

````
HpcJobInfoService: add: AlgorithmParameter: bootstrapSampleSize:0
HpcJobInfoService: add: AlgorithmParameter: completeRuleSetUsed:false
HpcJobInfoService: add: AlgorithmParameter: alpha:0.01
HpcJobInfoService: add: AlgorithmParameter: verbose:false
HpcJobInfoService: add: AlgorithmParameter: maxPathLength:-1
HpcJobInfoService: add: AlgorithmParameter: bootstrapEnsemble:1
HpcJobInfoService: add: AlgorithmParameter: maxDegree:100
HpcJobInfoService: add: AlgorithmParameter: penaltyDiscount:2.0
HpcJobInfoService: add: AlgorithmParameter: faithfulnessAssumed:true
HpcJobInfoService: add: JvmOptions: maxHeapSize: 5
%d [%thread] %-5level %logger - %msg%n08:24:21.247 [Thread-11] ERROR edu.cmu.tetradapp.editor.GeneralAlgorithmEditor - Unable to run algorithm.
org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:59)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:95)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:207)
	at org.hibernate.dialect.identity.GetGeneratedKeysDelegate.executeAndExtract(GetGeneratedKeysDelegate.java:57)
	at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:42)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2855)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3426)
	at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:81)
	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:619)
	at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:273)
	at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:254)
	at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:299)
	at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:317)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:272)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:178)
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:109)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:192)
	at org.hibernate.event.internal.DefaultSaveEventListener.saveWithGeneratedOrRequestedId(DefaultSaveEventListener.java:38)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:177)
	at org.hibernate.event.internal.DefaultSaveEventListener.performSaveOrUpdate(DefaultSaveEventListener.java:32)
	at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:73)
	at org.hibernate.internal.SessionImpl.fireSave(SessionImpl.java:679)
	at org.hibernate.internal.SessionImpl.save(SessionImpl.java:671)
	at org.hibernate.internal.SessionImpl.save(SessionImpl.java:666)
	at edu.pitt.dbmi.tetrad.db.service.HpcJobInfoService.add(HpcJobInfoService.java:56)
	at edu.cmu.tetradapp.app.hpc.manager.HpcJobManager.submitNewHpcJobToQueue(HpcJobManager.java:134)
	at edu.cmu.tetradapp.editor.GeneralAlgorithmEditor.doRemoteCompute(GeneralAlgorithmEditor.java:951)
	at edu.cmu.tetradapp.editor.GeneralAlgorithmEditor.access$600(GeneralAlgorithmEditor.java:123)
	at edu.cmu.tetradapp.editor.GeneralAlgorithmEditor$1.watch(GeneralAlgorithmEditor.java:1032)
	at edu.cmu.tetradapp.util.WatchedProcess$1.run(WatchedProcess.java:164)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: NOT NULL check constraint; SYS_CT_10105 table: ALGORITHMPARAMREQUEST column: DATAVALIDATIONID
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:204)
	... 28 common frames omitted
Caused by: org.hsqldb.HsqlException: integrity constraint violation: NOT NULL check constraint; SYS_CT_10105 table: ALGORITHMPARAMREQUEST column: DATAVALIDATIONID
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.Table.enforceRowConstraints(Unknown Source)
	at org.hsqldb.Table.insertSingleRow(Unknown Source)
	at org.hsqldb.StatementDML.insertRowSet(Unknown Source)
	at org.hsqldb.StatementInsert.getResult(Unknown Source)
	at org.hsqldb.StatementDMQL.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 31 common frames omitted
%d [%thread] %-5level %logger - %msg%nException in thread "Timer-0" org.hibernate.AssertionFailure: null id in edu.pitt.dbmi.tetrad.db.entity.AlgorithmParamRequest entry (don't flush the Session after an exception occurs)
	at org.hibernate.event.internal.DefaultFlushEntityEventListener.checkId(DefaultFlushEntityEventListener.java:60)
	at org.hibernate.event.internal.DefaultFlushEntityEventListener.getValues(DefaultFlushEntityEventListener.java:175)
	at org.hibernate.event.internal.DefaultFlushEntityEventListener.onFlushEntity(DefaultFlushEntityEventListener.java:135)
	at org.hibernate.event.internal.AbstractFlushingEventListener.flushEntities(AbstractFlushingEventListener.java:216)
	at org.hibernate.event.internal.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:85)
	at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:44)
	at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1251)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1319)
	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:87)
	at edu.pitt.dbmi.tetrad.db.service.HpcAccountService.get(HpcAccountService.java:65)
	at edu.cmu.tetradapp.app.hpc.manager.HpcAccountManager.getHpcAccounts(HpcAccountManager.java:27)
	at edu.cmu.tetradapp.app.hpc.task.HpcJobsScheduledTask.run(HpcJobsScheduledTask.java:52)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

````

**Comment by yuanzhou** [comment]
@jdramsey just FYI, this is the work that @chirayukong did to reflect the REST API changes I made a few weeks ago. In the updated causal REST API, we are exposing all the algorithms with those java annotations. Previously, we only had FGES and GFCI available in the API and users could only run jobs on HPC for these two algorithms as a result.

I've tested and will merge.

**Comment by jdramsey** [comment]
@yuanzhou Awesome! You'll have to show me how to use it!

**Comment by yuanzhou** [comment]
@jdramsey here is a quick guide after you pull the latest development branch:

1. Go to https://cloud.ccd.pitt.edu/ccd-web/login and register an account. At this point the causal web is solely used for API authentication. 

2. Set the HPC connection and save it at Tetrad: 





3. Run any Search as usual, the Tetrad UI will ask if execute the job on HPC, in this case, Amazon Web Services.



Then wait until the job is done in the cloud, we'll be able to see the generated graph. Pretty neat!

**Comment by chirayukong** [comment]
@jdramsey make sure that you delete the old HSQLDB because we changed its schema.
> rm -rf ~/.tetrad_workspace

**Comment by chirayukong** [comment]
FYI, we don't support multiple-dataset algorithms yet.

**Comment by cg09** [comment]
So IMaGES algorithms do not work?

**Comment by yuanzhou** [comment]
@cg09 according to Jeremy and Creg, for this round we just expose more algorithms via the REST API. 

Below are the supported algorithms in the API:

````
[
    {
        "id": "bpc",
        "name": "BPC",
        "description": "",
        "requireTest": false,
        "requireScore": false,
        "acceptKnowledge": true
    },
    {
        "id": "fas",
        "name": "FAS",
        "description": "",
        "requireTest": true,
        "requireScore": false,
        "acceptKnowledge": true
    },
    {
        "id": "fask",
        "name": "FASK",
        "description": "",
        "requireTest": false,
        "requireScore": true,
        "acceptKnowledge": true
    },
    {
        "id": "fask-concatenated",
        "name": "FASK Concatenated",
        "description": "",
        "requireTest": false,
        "requireScore": true,
        "acceptKnowledge": true
    },
    {
        "id": "fci",
        "name": "FCI",
        "description": "",
        "requireTest": true,
        "requireScore": false,
        "acceptKnowledge": true
    },
    {
        "id": "fges",
        "name": "FGES",
        "description": "",
        "requireTest": false,
        "requireScore": true,
        "acceptKnowledge": true
    },
    {
        "id": "fges-mb",
        "name": "FGES-MB",
        "description": "",
        "requireTest": false,
        "requireScore": true,
        "acceptKnowledge": true
    },
    {
        "id": "fofc",
        "name": "FOFC",
        "description": "",
        "requireTest": false,
        "requireScore": false,
        "acceptKnowledge": true
    },
    {
        "id": "ftfc",
        "name": "FTFC",
        "description": "",
        "requireTest": false,
        "requireScore": false,
        "acceptKnowledge": true
    },
    {
        "id": "gfci",
        "name": "GFCI",
        "description": "",
        "requireTest": true,
        "requireScore": true,
        "acceptKnowledge": true
    },
    {
        "id": "glasso",
        "name": "GLASSO",
        "description": "",
        "requireTest": false,
        "requireScore": false,
        "acceptKnowledge": false
    },
    {
        "id": "imgs_cont",
        "name": "IMaGES Continuous",
        "description": "",
        "requireTest": false,
        "requireScore": false,
        "acceptKnowledge": true
    },
    {
        "id": "imgs_disc",
        "name": "IMaGES Discrete",
        "description": "",
        "requireTest": false,
        "requireScore": false,
        "acceptKnowledge": true
    },
    {
        "id": "mbfs",
        "name": "MBFS",
        "description": "",
        "requireTest": true,
        "requireScore": false,
        "acceptKnowledge": true
    },
    {
        "id": "mgm",
        "name": "MGM",
        "description": "",
        "requireTest": false,
        "requireScore": false,
        "acceptKnowledge": false
    },
    {
        "id": "mimbuild",
        "name": "MIMBuild",
        "description": "",
        "requireTest": false,
        "requireScore": false,
        "acceptKnowledge": false
    },
    {
        "id": "pc-all",
        "name": "PC All",
        "description": "",
        "requireTest": true,
        "requireScore": false,
        "acceptKnowledge": true
    },
    {
        "id": "rfci",
        "name": "RFCI",
        "description": "",
        "requireTest": true,
        "requireScore": false,
        "acceptKnowledge": true
    },
    {
        "id": "ts-fci",
        "name": "TsFCI",
        "description": "",
        "requireTest": true,
        "requireScore": false,
        "acceptKnowledge": true
    },
    {
        "id": "ts-gfci",
        "name": "TsGFCI",
        "description": "",
        "requireTest": true,
        "requireScore": true,
        "acceptKnowledge": true
    },
    {
        "id": "ts-imgs",
        "name": "TsIMaGES",
        "description": "",
        "requireTest": false,
        "requireScore": true,
        "acceptKnowledge": true
    }
]
````

**Comment by yuanzhou** [comment]
Actually those  IMaGES algorithms are exposed too as well, we just won't be able to handle multiple datasets in one query through the REST API at this point. But you can still run those algorithms with a single dataset per request. We'll need to put more thoughts into the API design.

**Comment by chirayukong** [comment]
@cg09 The REST API accepts only a dataset id (integer type) as its parameter. Therefore, I need to opt out any multiple datasets' request. However, IMaGES (imgs_cont and imgs_cont) works but only with a single dataset.

**Pull request merged**
