### PR TITLE
Updated CStaR and added BOSS and restricted BOSS.

### PR DESCRIPTION
**Pull request by jdramsey**

### CODE REVIEW

**Review by bja43 — APPROVED** [review]
everything seems to be working

**Comment by jdramsey** [comment]
Great!

**Comment by cg09** [comment]
What is "restricted BOSS"?

**Comment by jdramsey** [comment]
It's the algorithm I described to you earlier--use BOSS itself with knowledge to find the nodes in the anteriority of the targets, and then run BOSS over this selection of variables.

**Pull request merged**
