### PR TITLE
Fixed verbosity issues, "verbose" last issue, data type for some continuous searches.

### PR DESCRIPTION
**Pull request by jdramsey**

### CODE REVIEW

**Comment by jdramsey** [comment]
https://github.com/cmu-phil/tetrad/issues/1109

**Comment by jdramsey** [comment]
To test the verbosity issues, run searches using PC, FCI, FGES, FOFC, with logging turned on in the interface. Verbose output should appear (independence test info, score into, etc.)

To test "verbose" last issue, just go through the algorithms in the interface and make sure that no matter which algorithm you pick, the "verbose" option comes out last. (Maybe there's a better way to do this, come to think about it, than just checking it on an algorithm by algorithm basis.)

For the data type issue, make sure the following algorithms are filtered out for discrete and mixed data: R3, Skew, RSkew, LiNGAM, GLASSO.

**Comment by jdramsey** [comment]
Also, if this is accepted, could you please let me know how Peter and Clark can get a build with these changes?

**Comment by yuanzhou** [comment]
I just tested verbose logging, worked fine with PC, FCI, FGES. But when I ran FOFC on continuous data, I got this error:

Capture

And if I checked "No" for MimBuild, I went through but no logging.

Capture

**Comment by jdramsey** [comment]
I see. That's supposed to take a MIM model. If you make a random graph but select the MIM option you should get a pure measurement model, and it should work. But we need a better error message. Let me see if I can make a better error message.

**Comment by yuanzhou** [comment]
Oh I see. Just simulated the Random One Factor MIM for continuous data and the logging worked fine with FOFC.

**Comment by jdramsey** [comment]
OK, I changed the error message to be something more informative. Is this better?

Screen Shot 2019-05-03 at 11 30 08 AM

**Comment by jdramsey** [comment]
Nice! It works!

**Comment by yuanzhou** [comment]
Much better error message! And the `DataType.continuous` annotation you added in R3, Skew, RSkew, LiNGAM, GLASSO works well for filtering.

**Comment by yuanzhou** [comment]
Just came to my mind that should you also annotate FOFC and FTFC for continuous data only? So we don't see them with discrete and mixed data?

**Comment by jdramsey** [comment]
Great!

**Pull request merged**
