### PR TITLE
Fixed issues with test cases 2 & 3.

### PR DESCRIPTION
**Pull request by amurrayw**
Fixed.

### CODE REVIEW

**Comment by jdramsey** [comment]
It works!!!! :) I have two phantom files that keep popping up, but that's my problem. :)

**Comment by amurrayw** [comment]
That could be my code. Due to the amount of time it takes for GES/PC to run on the 30,000 variable datasets I've been using, I wrote the code so that that it saves the discovered non-latent dependencies to a text file. That way, if there is a bug in the latent structure code I wouldn't have to start from scratch.

**Comment by jdramsey** [comment]
Thanks! Merging in a second...

On Sat, Nov 21, 2015 at 1:06 PM, Alexander Murray-Watters <
notifications@github.com> wrote:

> That could be my code. Due to the amount of time it takes for GES/PC to
> run on the 30,000 variable datasets I've been using, I wrote the code so
> that that it saves the discovered non-latent dependencies to a text file.
> That way, if there is a bug in the latent structure code I wouldn't have to
> start from scratch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-phil/tetrad/pull/67#issuecomment-158667840>.
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Comment by jdramsey** [comment]
Never mind, this is an old email I missed. Thanks though.

On Sat, Nov 21, 2015 at 1:23 PM, Joseph Ramsey <jdramsey@andrew.cmu.edu>
wrote:

> Thanks! Merging in a second...
>
> On Sat, Nov 21, 2015 at 1:06 PM, Alexander Murray-Watters <
> notifications@github.com> wrote:
>
>> That could be my code. Due to the amount of time it takes for GES/PC to
>> run on the 30,000 variable datasets I've been using, I wrote the code so
>> that that it saves the discovered non-latent dependencies to a text file.
>> That way, if there is a bug in the latent structure code I wouldn't have to
>> start from scratch.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cmu-phil/tetrad/pull/67#issuecomment-158667840>.
>>
>
>
>
> --
> Joseph D. Ramsey
> Special Faculty and Director of Research Computing
> Department of Philosophy
> 135 Baker Hall
> Carnegie Mellon University
> Pittsburgh, PA 15213
>
> jsph.ramsey@gmail.com
> Office: (412) 268-8063
> http://www.andrew.cmu.edu/user/jdramsey
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey

**Pull request merged**
