### PR TITLE
Recent fixes toward release.

### PR DESCRIPTION
**Pull request by jdramsey**

### CODE REVIEW

**Comment by jdramsey** [comment]
Additional fixes starting 2022-3-29:

1. Cleaned up edu.cmu.tetrad packages.
2. Cleaned up edu.cmu.tetradapp packages.
3. Repaired and re-added CStaR to the interface as experimental. To see the table you need to open the logging window; it is also printed to the command line.
4. Made printing of p-values for independence tests uniform across Tetrad.
5. Set seed on TestCellProbabilities so that it would return a consistent result.
6. Changed the name of the main “About” menu to the more standard “Help”.
7. Added a menu item to to the main Help menu to launch the HTML manual in the development branch.
8. Adjusted copyright notices throughout code.
9. Re-added the underlinings display, to show ambiguous triples, underlinings, and dotted underlinings in a graph. It’s re-added to the Graph menu in the Graph Editor.
10. Fixed a bug introduced in this version where Display Subgraphs could not be shown as a child to Search.
11. Re-classified grasp-tol as experimental. Verified that the experimental algorithms can be made to show up by modifying the settings.
12. (Re-)set simulation box to show data after simulation after a new simulation is done.
13. Fixed some inconsistencies in the bootstrapping API, where bootstrapping parameters were not being passed or honored correctly.
14. Fixed GRaSP and GRaSP-FCI so that they use the tolerance depth parameter.
15. Fixed a null pointer preventing the cluster editor from opening with no parents.
16. Fixed a problem in which selected scores and tests in the Search box were not remembered when doing a new search with new data.
17. Commented out the Independence Facts knowledge option, as it’s not working. This is supposed to let the user store a list of independence facts entered manually.
18. Re-added CCD (Cyclic Causal Discovery) to the interface.
19. Added a description for CCD to the manual.
20. Added a note to the manual warning of coefficients that are too large for cyclic models.
21. Switched DAG and SEM Graph editors over to using the tabbed panes for the “Edges” displays.
22. Added Peter’s algorithm flowchart to the Help menu.
23. Adjusted copyright text in the Help menu and the main copyright notice in the repository to reflect the current year.
24. Fixed typo in text that comes up if you try to launch a session box with the wrong inputs.
25. Added a list of contributors to the project to the Help menu.
26. Changed “Save session to directory…” in a save dialog to “Save to directory…” since this method is used for more than sessions.
27. Renamed MuiltiFask bak to FASK-Vote (to align with internal algorithm).
28. Fixed a problem with FASK and FASK-Vote where bootstrapping was throwing an exception.
29. Adjusted random graph editor so that connected graphs are returned unless none can be found, in which case an empty graph is returned.
30. Fixed wording, “Yes if adding an original dataset as a bootstrapping” to “Yes if adding the original dataset…“.
31. Fixed a problem introduced in the file cleanup where you couldn’t launch a time lag graph editor.
32. Added a ‘timeLag’ parameter to all relevant causally insufficient and sufficient algorithms to automatically apply the time lag transform.
33. Adjusted manual entries for the new time lag parameters.
34. Compiling under Java JDK 1.8 to fix a data loading problem reported by several people. (Joe-a culpa.)
35. Clarified instructions in the manual for using the (perhaps confusing) standardized SEM IM editor.

**Comment by jdramsey** [comment]
@kvb2univpitt This should be it! All outstanding issues fixed! I believe we simply need to merge this into development and then make a jar under 1.8 to email to the group. Then we can think about a release.

**Comment by kvb2univpitt** [comment]
All tests seem to pass.  Looks good on my end.

**Review by kvb2univpitt — APPROVED** [review]

**Comment by jdramsey** [comment]
Great, thanks!

**Pull request merged**
