### PR TITLE
Refactoring of the EdgeListGraph class.

### PR DESCRIPTION
**Pull request by jdramsey**
The EdgeListGraph class was refactored by pulling out code for Underlines and code for Paths (see). All path methods from EdgeListGraph and GraphUtils were moved to Paths. All other graph code was adjusted in the project for these changes.

Syntax is graph.paths().method(..), graph.underlines().method(..).

Compiles and all tests pass.

### CODE REVIEW

**Comment by jdramsey** [comment]
Also factored out graph persistence methods into GraphPersistence and data persistence method into DataPersistence. The mixed data method is still wrong.

**Comment by jdramsey** [comment]
Refactored classes to look at are Graph (interface), EdgeListGraph, Paths, Underlines, GraphUtils, DataUtils, GraphPersistence, DataPersistence.

**Review by kvb2univpitt — COMMENTED** [review]
All tests have passed in Linux.  I also test with simple search algorithm.  Everything seems stable. @bja43 Joe suggests you should have the final look.  Please approve and merge if you're satisfied with the changes.

**Review by bja43 — APPROVED** [review]
I was able to compile and run a few tests without issue.

**Pull request merged**
