### PR TITLE
Adjusted some defaults for discrete searches to optimize performance.

### PR DESCRIPTION
**Pull request by jdramsey**
https://github.com/cmu-phil/tetrad/issues/1090

### CODE REVIEW

**Comment by jdramsey** [comment]
@yuanzhou I edited the manual a bit. I couldn't figure out a good way to give the discrete searches different defaults for alpha so I just noted in the manual that for discrete searches the default should be 0.05 for Chi Square and G Square. Otherwise, as in https://github.com/cmu-phil/tetrad/issues/1090.

**Comment by jdramsey** [comment]
@yuanzhou I standardized the simulation parameters mentioned in https://github.com/cmu-phil/tetrad/issues/1087. Now it should be the case that:

- The following have post-processing discretization parameters.

   * None. The only simulation methods with discretization parameters are the mixed variable simulations, Lee & Hastie and Conditional Gaussian.

- The following methods should have a "standardize" parameter:

   * SEM Simulation
   * Linear Fisher
   * Time Series Simulation

- The following methods should have a method to randomly reorder columns:

   * All but Time Series Simulation.

**Comment by jdramsey** [comment]
@yuanzhou Please don't merge this quite yet. Some further issues from Clark.

**Comment by jdramsey** [comment]
@yuanzhou OK, this is good I think. I wrote a script to help find defaults for the parameters for discrete searches, which I'm committing with this pull request. I set the priors to the ones listed. I played around a lot with discrete searches, but I think I put everything back to the way it was, except where noted.

**Comment by yuanzhou** [comment]
Looking at this now

**Comment by yuanzhou** [comment]
@jdramsey can you please describe couple of the testing cases so I know where to look at and don't miss any intended uses? I looked at the code but was not clear about the test cases.

**Comment by jdramsey** [comment]
Well, I mean, what you could do would be to re-run the script I included for, say, sample size 500 and see if you agree with the defaults I picked. They should be for models that occur near the top the output under the Average Statistics section. One of the pushes I did was for that script. All you need to do is run the script; it should be automatic.

**Comment by yuanzhou** [comment]
[Discrete_Searches_Sample_Size_5000.txt](https://github.com/cmu-phil/tetrad/files/3109405/Discrete_Searches_Sample_Size_5000.txt)

[Discrete_Searches_Sample_Size_500.txt](https://github.com/cmu-phil/tetrad/files/3109406/Discrete_Searches_Sample_Size_500.txt)

@jdramsey Here are the results I got for sample size 5000 and 500. I can merge this pull request if they look good. You much have a better idea about the defaults.

**Comment by jdramsey** [comment]
Sorry, there is a file for each that would have appeared in your tetrad directory. Do you see them?

**Comment by jdramsey** [comment]
They're in a folder called comparison.discrete.* something. Those contain all of the rankings of the models.

**Comment by yuanzhou** [comment]
Ohh, I was wondering about the Average Statistics section you mentioned but didn't see them in the output. 

Here are the rankings:


[comparison_all_5000.txt](https://github.com/cmu-phil/tetrad/files/3109497/comparison_all_5000.txt)
[comparison_all_500.txt](https://github.com/cmu-phil/tetrad/files/3109498/comparison_all_500.txt)

**Comment by jdramsey** [comment]
Perfect. Your N = 500 came out even better than mine:

**Comment by jdramsey** [comment]
I guess I can also say, if make a random Bayes net with 3 categories per node, average degree 2, and search it using FGES/BDeu or PC with the CPC option, with these defaults, you should get a result which is very close to the pattern of the true graph. That was the idea.

Just giving recommendations to people as to what algorithms and settings to use.

**Pull request merged**
