### PR TITLE
Added initial round of test cases...

### PR DESCRIPTION
**Pull request by amurrayw**
Hi Joe,

Fixed up my basic test cases. I'll likely add more (and will also clean up the test file), but this will help us flag anything that induces major breakage. 

Best,

Alexander

### CODE REVIEW

**Comment by jdramsey** [comment]
Test 2 and 3 are failing for me; I disabled them so all the unit tests would pass. Are they passing for you?

**Comment by amurrayw** [comment]
They were when I made the pull request. I'll double check though.

- Alexander



On Fri, Nov 20, 2015 at 3:28 PM, jdramsey <notifications@github.com> wrote:

> Test 2 and 3 are failing for me; I disabled them so all the unit tests
> would pass. Are they passing for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-phil/tetrad/pull/66#issuecomment-158555878>.
>



-- 

Alexander Murray-Watters
Logic, Computation, and Methodology M.S.
Carnegie Mellon University
amurrayw@cmu.edu

**Comment by amurrayw** [comment]
I've fixed test case 2, I'll fix test case 3 as well (something silly
happened when I moved the old test file over to the git repo).

On Fri, Nov 20, 2015 at 3:29 PM, Alexander Murray-Watters <
ajgmw5565@gmail.com> wrote:

> They were when I made the pull request. I'll double check though.
>
> - Alexander
>
>
>
> On Fri, Nov 20, 2015 at 3:28 PM, jdramsey <notifications@github.com>
> wrote:
>
>> Test 2 and 3 are failing for me; I disabled them so all the unit tests
>> would pass. Are they passing for you?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cmu-phil/tetrad/pull/66#issuecomment-158555878>.
>>
>
>
>
> --
>
> Alexander Murray-Watters
> Logic, Computation, and Methodology M.S.
> Carnegie Mellon University
> amurrayw@cmu.edu
>



-- 

Alexander Murray-Watters
Logic, Computation, and Methodology M.S.
Carnegie Mellon University
amurrayw@cmu.edu

**Comment by amurrayw** [comment]
Fixed in latest pull request.

On Friday, November 20, 2015, Alexander Murray-Watters <ajgmw5565@gmail.com>
wrote:

> I've fixed test case 2, I'll fix test case 3 as well (something silly
> happened when I moved the old test file over to the git repo).
>
> On Fri, Nov 20, 2015 at 3:29 PM, Alexander Murray-Watters <
> ajgmw5565@gmail.com <javascript:_e(%7B%7D,'cvml','ajgmw5565@gmail.com');>>
> wrote:
>
>> They were when I made the pull request. I'll double check though.
>>
>> - Alexander
>>
>>
>>
>> On Fri, Nov 20, 2015 at 3:28 PM, jdramsey <notifications@github.com
>> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>>
>>> Test 2 and 3 are failing for me; I disabled them so all the unit tests
>>> would pass. Are they passing for you?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/cmu-phil/tetrad/pull/66#issuecomment-158555878>.
>>>
>>
>>
>>
>> --
>>
>> Alexander Murray-Watters
>> Logic, Computation, and Methodology M.S.
>> Carnegie Mellon University
>> amurrayw@cmu.edu <javascript:_e(%7B%7D,'cvml','amurrayw@cmu.edu');>
>>
>
>
>
> --
>
> Alexander Murray-Watters
> Logic, Computation, and Methodology M.S.
> Carnegie Mellon University
> amurrayw@cmu.edu <javascript:_e(%7B%7D,'cvml','amurrayw@cmu.edu');>
>


-- 

Alexander Murray-Watters
Logic, Computation, and Methodology M.S.
Carnegie Mellon University
amurrayw@cmu.edu

**Pull request merged**
