### PR TITLE
Added Comparison.compareFromGraphs methods (based on existing methods that were previously debugged, the names of which were changed as per spec).

### PR DESCRIPTION
**Pull request by jdramsey**

### CODE REVIEW

**Comment by kvb2univpitt** [comment]
@jdramsey Didn't you say you need to do some more testing on this?  Or, can I go ahead and play around with this?

**Comment by cg09** [comment]
Kevin,

Thanks for keeping at all of this. Really thanks.

Clark

**Comment by kvb2univpitt** [comment]
@cg09 You're welcome.  :)

**Comment by jdramsey** [comment]
Maybe we could talk briefly about what this is supposed to do from the user's point of view? I may not be clear on it.

**Comment by cg09** [comment]
Not sure.

**Comment by kvb2univpitt** [comment]
@jdramsey Ok.  We can talk about it after our meeting on Monday at 2:00 PM.  Thanks.

**Comment by jdramsey** [comment]
Too old to merge....

**Pull request closed without merging**
