### PR TITLE
Kevin data filter

### PR DESCRIPTION
**Pull request by kvb2univpitt**
A fix for issue #1368.

### CODE REVIEW

**Review by jdramsey — COMMENTED** [review]
This is much better!! The only issue is that the "Score:" dropdown is hidden now in the default layout. Could the stuff above it be scrunched up? One way to do it I thought of is to take out two of the (obvious) instructions, as indicated in the images below. Is that OK? I commented the out in a hacky way; probably if you like this you should do it though.

Screen Shot 2022-03-21 at 7 47 35 AM
Screen Shot 2022-03-21 at 7 48 56 AM

**Comment by jdramsey** [comment]
Well, that is, "Score:" is hidden on _my_ machine.

**Comment by jdramsey** [comment]
Oh, and obviously I'll need to add a description for FASK-PW, I'll do that. I added several; I thought I'd gotten them all, sorry.

**Comment by kvb2univpitt** [comment]
Ok.  Try it now.  I changed the default size.

**Pull request merged**
