### PR TITLE
LiNGAM and LiNG-D code

### PR DESCRIPTION
**Pull request by jdramsey**
Please check the following classes:

Lingam
LingD
NRooks
TestLing

Please run the tests in TestLing to make sure they work. Still more work to do but hopefully this is a good start.

### CODE REVIEW

**Comment by cg09** [comment]
What is NRooks?

**Comment by bja43** [comment]
/**
     * Returns W, permuted rowwise by the permutation passed in through the constructor.
     * @return The row-permuted W.
     */
    public Matrix getPermutedMatrix() {
        return M.getSelection(rowPerm, colPerm);
    }

Should the comment here say rowwise and column wise?

**Comment by jdramsey** [comment]
Thanks, fixed.

**Comment by bja43** [comment]
I noticed that "strongestDiagonalByCols" in the LingD class is unused within the class, but is used in the Lingam class. Would it make sense to move this method to the Lingam class?

**Comment by bja43** [comment]
pairsNRook and nRooks are unused (for calls to the latter, you can call pairNRooks directly)

**Comment by bja43** [comment]
The class variable spineThreshold is unused (it is only used in the nRooks method call and nRooks does not utilize the passed parameter).

**Review by bja43 — APPROVED** [review]
Code looks good to me.

**Pull request merged**
