### PR TITLE
Changes for Wednesday's release

### PR DESCRIPTION
**Pull request by jdramsey**

### CODE REVIEW

**Comment by kvb2univpitt** [comment]
@jdramsey I was not able to comple tetrad-lib.  I got a bunch of errors relating to the javadoc and other classes:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.6.3:jar (attach-javadocs) on project tetrad-lib: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/search/Fci.java:57: warning: empty <p> tag
[ERROR]  * <p>
[ERROR]    ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/bayes/BayesProperties.java:107: warning: no @return
[ERROR]     public LikelihoodRet getLikelihoodRatioP(Graph graph) {
[ERROR]                          ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/bayes/BayesProperties.java:434: warning: no comment
[ERROR]     public class LikelihoodRet {
[ERROR]            ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/bayes/BayesProperties.java:52: warning: no comment
[ERROR]     public BayesProperties(DataSet dataSet) {
[ERROR]            ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/bayes/BayesProperties.java:394: warning: no comment
[ERROR]     public int getSampleSize() {
[ERROR]                ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/bayes/BayesProperties.java:398: warning: no comment
[ERROR]     public Node getVariable(String targetName) {
[ERROR]                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/bayes/BayesProperties.java:436: warning: no comment
[ERROR]         public double bic;
[ERROR]                       ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/bayes/BayesProperties.java:437: warning: no comment
[ERROR]         public double chiSq;
[ERROR]                       ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/bayes/BayesProperties.java:438: warning: no comment
[ERROR]         public double dof;
[ERROR]                       ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/bayes/BayesProperties.java:435: warning: no comment
[ERROR]         public double p;
[ERROR]                       ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/bayes/BayesUpdater.java:39: warning: no comment
[ERROR]     long serialVersionUID = 23L;
[ERROR]          ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/bayes/BayesXmlParser.java:109: warning: no comment
[ERROR]     public BayesIm getBayesIm(Element element) {
[ERROR]                    ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/bayes/BayesXmlRenderer.java:39: warning: no comment
[ERROR]     public static Element getElement(BayesIm bayesIm) {
[ERROR]                           ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/pitt/dbmi/algo/bayesian/constraint/inference/BCCausalInference.java:429: warning: no comment
[ERROR]     public enum OP {
[ERROR]            ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/pitt/dbmi/algo/bayesian/constraint/inference/BCCausalInference.java:47: warning: no comment
[ERROR]     public BCCausalInference(int[] nodeDimension, int[][] cases) {
[ERROR]            ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/pitt/dbmi/algo/bayesian/constraint/inference/BCCausalInference.java:430: warning: no comment
[ERROR]         DEPENDENT,
[ERROR]         ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/pitt/dbmi/algo/bayesian/constraint/inference/BCCausalInference.java:431: warning: no comment
[ERROR]         INDEPENDENT
[ERROR]         ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/pitt/dbmi/algo/bayesian/constraint/inference/BCInference.java:516: warning: no comment
[ERROR]     public enum OP {
[ERROR]            ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/pitt/dbmi/algo/bayesian/constraint/inference/BCInference.java:512: warning: no comment
[ERROR]     public void setPriorEqivalentSampleSize(double priorEquivalentSampleSize) {
[ERROR]                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/pitt/dbmi/algo/bayesian/constraint/inference/BCInference.java:518: warning: no comment
[ERROR]         independent, dependent
[ERROR]                      ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/pitt/dbmi/algo/bayesian/constraint/inference/BCInference.java:518: warning: no comment
[ERROR]         independent, dependent
[ERROR]         ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/bayes/BdeMetricCache.java:75: warning: no @param for node
[ERROR]     public double scoreLnGam(Node node, Set<Node> parents, BayesPm bayesPmMod,
[ERROR]                   ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/bayes/BdeMetricCache.java:75: warning: no @param for parents
[ERROR]     public double scoreLnGam(Node node, Set<Node> parents, BayesPm bayesPmMod,
[ERROR]                   ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/bayes/BdeMetricCache.java:75: warning: no @param for bayesPmMod
[ERROR]     public double scoreLnGam(Node node, Set<Node> parents, BayesPm bayesPmMod,
[ERROR]                   ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/bayes/BdeMetricCache.java:75: warning: no @param for bayesIm
[ERROR]     public double scoreLnGam(Node node, Set<Node> parents, BayesPm bayesPmMod,
[ERROR]                   ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/bayes/BdeMetricCache.java:75: warning: no @return
[ERROR]     public double scoreLnGam(Node node, Set<Node> parents, BayesPm bayesPmMod,
[ERROR]                   ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/bayes/BdeMetricCache.java:445: warning: no @param for node
[ERROR]     public double[][] getObservedCounts(Node node, BayesPm bayesPm,
[ERROR]                       ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/bayes/BdeMetricCache.java:445: warning: no @param for bayesPm
[ERROR]     public double[][] getObservedCounts(Node node, BayesPm bayesPm,
[ERROR]                       ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/bayes/BdeMetricCache.java:445: warning: no @param for bayesIm
[ERROR]     public double[][] getObservedCounts(Node node, BayesPm bayesPm,
[ERROR]                       ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/bayes/BdeMetricCache.java:445: warning: no @return
[ERROR]     public double[][] getObservedCounts(Node node, BayesPm bayesPm,
[ERROR]                       ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/bayes/BdeMetricCache.java:465: warning: no @param for node
[ERROR]     public int getScoreCount(Node node, Set<Node> parents) {
[ERROR]                ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/bayes/BdeMetricCache.java:465: warning: no @param for parents
[ERROR]     public int getScoreCount(Node node, Set<Node> parents) {
[ERROR]                ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/bayes/BdeMetricCache.java:465: warning: no @return
[ERROR]     public int getScoreCount(Node node, Set<Node> parents) {
[ERROR]                ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/bayes/BdeMetricCache.java:63: warning: no comment
[ERROR]     public BdeMetricCache(DataSet dataSet, BayesPm bayesPm) {
[ERROR]            ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/algcomparison/score/ScoreWrapper.java:55: warning: no @return
[ERROR]     Node getVariable(String name);
[ERROR]          ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/search/utils/BesPermutation.java:230: warning: no comment
[ERROR]     public Knowledge getKnowledge() {
[ERROR]                      ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/algcomparison/algorithm/oracle/pag/Bfci.java:62: warning: no comment
[ERROR]     public Bfci(IndependenceWrapper test, ScoreWrapper score) {
[ERROR]            ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/algcomparison/algorithm/ReturnsBootstrapGraphs.java:9: warning: no comment
[ERROR]     List<Graph> getBootstrapGraphs();
[ERROR]                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/algcomparison/utils/TakesIndependenceWrapper.java:10: warning: no comment
[ERROR]     IndependenceWrapper getIndependenceWrapper();
[ERROR]                         ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/algcomparison/utils/UsesScoreWrapper.java:10: warning: no comment
[ERROR]     ScoreWrapper getScoreWrapper();
[ERROR]                  ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/algcomparison/utils/TakesIndependenceWrapper.java:12: warning: no comment
[ERROR]     void setIndependenceWrapper(IndependenceWrapper independenceWrapper);
[ERROR]          ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/algcomparison/utils/UsesScoreWrapper.java:12: warning: no comment
[ERROR]     void setScoreWrapper(ScoreWrapper score);
[ERROR]          ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/algcomparison/statistic/BicDiff.java:41: warning: no comment
[ERROR]     public void setPrecomputeCovariances(boolean precomputeCovariances) {
[ERROR]                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/algcomparison/statistic/BicDiffPerRecord.java:46: warning: no comment
[ERROR]     public void setPrecomputeCovariances(boolean precomputeCovariances) {
[ERROR]                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/algcomparison/statistic/BicEst.java:25: warning: no comment
[ERROR]     public BicEst() {
[ERROR]            ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/algcomparison/statistic/BicEst.java:74: warning: no comment
[ERROR]     public void setPrecomputeCovariances(boolean precomputeCovariances) {
[ERROR]                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/algcomparison/statistic/BicTrue.java:40: warning: no comment
[ERROR]     public void setPrecomputeCovariances(boolean precomputeCovariances) {
[ERROR]                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/algcomparison/statistic/utils/BidirectedConfusion.java:21: warning: no comment
[ERROR]     public BidirectedConfusion(Graph truth, Graph est) {
[ERROR]            ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/algcomparison/statistic/utils/BidirectedConfusion.java:67: warning: no comment
[ERROR]     public int getFn() {
[ERROR]                ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/algcomparison/statistic/utils/BidirectedConfusion.java:63: warning: no comment
[ERROR]     public int getFp() {
[ERROR]                ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/algcomparison/statistic/utils/BidirectedConfusion.java:71: warning: no comment
[ERROR]     public int getTn() {
[ERROR]                ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/algcomparison/statistic/utils/BidirectedConfusion.java:59: warning: no comment
[ERROR]     public int getTp() {
[ERROR]                ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/algorithm/biolingua/Biolingua.java:84: warning: no @param for correlMatrix
[ERROR]     public static synchronized BiolinguaDigraph BiolinguaAlgorithm(
[ERROR]                                                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/algorithm/biolingua/Biolingua.java:84: warning: no @param for initGraph
[ERROR]     public static synchronized BiolinguaDigraph BiolinguaAlgorithm(
[ERROR]                                                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/algorithm/biolingua/Biolingua.java:84: warning: no @return
[ERROR]     public static synchronized BiolinguaDigraph BiolinguaAlgorithm(
[ERROR]                                                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/algorithm/biolingua/Biolingua.java:101: warning: no @param for correlMatrix
[ERROR]     public static synchronized BiolinguaDigraph BiolinguaAlgorithm(
[ERROR]                                                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/algorithm/biolingua/Biolingua.java:101: warning: no @param for initGraph
[ERROR]     public static synchronized BiolinguaDigraph BiolinguaAlgorithm(
[ERROR]                                                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/algorithm/biolingua/Biolingua.java:101: warning: no @param for vBitsAnnotat
[ERROR]     public static synchronized BiolinguaDigraph BiolinguaAlgorithm(
[ERROR]                                                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/algorithm/biolingua/Biolingua.java:101: warning: no @param for vBitsErrors
[ERROR]     public static synchronized BiolinguaDigraph BiolinguaAlgorithm(
[ERROR]                                                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/algorithm/biolingua/Biolingua.java:101: warning: no @param for vbitsLinks
[ERROR]     public static synchronized BiolinguaDigraph BiolinguaAlgorithm(
[ERROR]                                                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/algorithm/biolingua/Biolingua.java:101: warning: no @param for vBitsPredic
[ERROR]     public static synchronized BiolinguaDigraph BiolinguaAlgorithm(
[ERROR]                                                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/algorithm/biolingua/Biolingua.java:101: warning: no @return
[ERROR]     public static synchronized BiolinguaDigraph BiolinguaAlgorithm(
[ERROR]                                                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/algorithm/biolingua/Biolingua.java:114: warning: no @param for correlMatrix
[ERROR]     public static synchronized BiolinguaDigraph BiolinguaAlgorithm(
[ERROR]                                                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/algorithm/biolingua/Biolingua.java:114: warning: no @param for signifMatrix
[ERROR]     public static synchronized BiolinguaDigraph BiolinguaAlgorithm(
[ERROR]                                                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/algorithm/biolingua/Biolingua.java:114: warning: no @param for initGraph
[ERROR]     public static synchronized BiolinguaDigraph BiolinguaAlgorithm(
[ERROR]                                                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/algorithm/biolingua/Biolingua.java:114: warning: no @param for vBitsAnnotat
[ERROR]     public static synchronized BiolinguaDigraph BiolinguaAlgorithm(
[ERROR]                                                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/algorithm/biolingua/Biolingua.java:114: warning: no @param for vBitsErrors
[ERROR]     public static synchronized BiolinguaDigraph BiolinguaAlgorithm(
[ERROR]                                                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/algorithm/biolingua/Biolingua.java:114: warning: no @param for vbitsLinks
[ERROR]     public static synchronized BiolinguaDigraph BiolinguaAlgorithm(
[ERROR]                                                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/algorithm/biolingua/Biolingua.java:114: warning: no @param for vBitsPredic
[ERROR]     public static synchronized BiolinguaDigraph BiolinguaAlgorithm(
[ERROR]                                                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/algorithm/biolingua/Biolingua.java:114: warning: no @return
[ERROR]     public static synchronized BiolinguaDigraph BiolinguaAlgorithm(
[ERROR]                                                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/algorithm/biolingua/Digraph.java:66: warning: no @throws for java.io.IOException
[ERROR]     public Digraph(String fname) throws IOException {
[ERROR]            ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/algorithm/biolingua/Digraph.java:73: warning: no @param for digraph
[ERROR]     public Digraph(Digraph digraph) {
[ERROR]            ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/algorithm/biolingua/Digraph.java:172: warning: no @return
[ERROR]     public int[] getParents(int j) {
[ERROR]                  ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/algorithm/biolingua/BiolinguaDigraph.java:96: warning: no @return
[ERROR]     public boolean isParent(int p, int c) {
[ERROR]                    ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/algorithm/biolingua/BiolinguaDigraph.java:104: warning: no @return
[ERROR]     public String strOfParents(int i) {
[ERROR]                   ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/algorithm/biolingua/BiolinguaRunner.java:84: warning: no comment
[ERROR]     public static void main(String[] args) {
[ERROR]                        ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/history/BooleanFunction.java:85: warning: no @return
[ERROR]     public static BooleanFunction serializableInstance() {
[ERROR]                                   ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/history/BooleanFunction.java:110: warning: no @param for row
[ERROR]     public boolean getValue(int row) {
[ERROR]                    ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/history/BooleanFunction.java:110: warning: no @return
[ERROR]     public boolean getValue(int row) {
[ERROR]                    ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/history/BooleanFunction.java:121: warning: no @param for row
[ERROR]     public void setValue(int row, boolean value) {
[ERROR]                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/history/BooleanFunction.java:121: warning: no @param for value
[ERROR]     public void setValue(int row, boolean value) {
[ERROR]                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/history/BooleanFunction.java:138: warning: no @return
[ERROR]     public int getRow(boolean[] parentValues) {
[ERROR]                ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/history/BooleanFunction.java:153: warning: no @return
[ERROR]     public int getNumRows() {
[ERROR]                ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/history/BooleanFunction.java:160: warning: no @param for row
[ERROR]     public boolean[] getParentValues(int row) {
[ERROR]                      ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/history/BooleanFunction.java:160: warning: no @return
[ERROR]     public boolean[] getParentValues(int row) {
[ERROR]                      ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/history/BooleanFunction.java:192: warning: no @return
[ERROR]     public boolean isCanalyzing() {
[ERROR]                    ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/history/UpdateFunction.java:45: warning: no @return
[ERROR]     IndexedLagGraph getIndexedLagGraph();
[ERROR]                     ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/history/UpdateFunction.java:59: warning: no @return
[ERROR]     int getNumFactors();
[ERROR]         ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/history/UpdateFunction.java:64: warning: no @return
[ERROR]     int getMaxLag();
[ERROR]         ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/history/BooleanGlassFunction.java:199: warning: no @return
[ERROR]     public static BooleanGlassFunction serializableInstance() {
[ERROR]                                        ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/history/BooleanGlassFunction.java:215: warning: no @return
[ERROR]     public double getBasalExpression() {
[ERROR]                   ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/history/BooleanGlassFunction.java:222: warning: no @param for basalExpression
[ERROR]     public void setBasalExpression(double basalExpression) {
[ERROR]                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/history/BooleanGlassFunction.java:298: warning: no @param for factor
[ERROR]     public BooleanFunction getSubFunction(int factor) {
[ERROR]                            ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/history/BooleanGlassFunction.java:298: warning: no @return
[ERROR]     public BooleanFunction getSubFunction(int factor) {
[ERROR]                            ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/history/BooleanGlassFunction.java:305: warning: no @return
[ERROR]     public double getDecayRate() {
[ERROR]                   ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/history/BooleanGlassFunction.java:312: warning: no @param for decayRate
[ERROR]     public void setDecayRate(double decayRate) {
[ERROR]                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/history/BooleanGlassFunction.java:326: warning: no @return
[ERROR]     public double getBooleanInfluenceRate() {
[ERROR]                   ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/history/BooleanGlassFunction.java:334: warning: no @param for booleanInfluenceRate
[ERROR]     public void setBooleanInfluenceRate(double booleanInfluenceRate) {
[ERROR]                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/history/BooleanGlassFunction.java:348: warning: no @param for lowerBound
[ERROR]     public void setLowerBound(double lowerBound) {
[ERROR]                 ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/study/gene/tetrad/gene/history/BooleanGlassFunction.java:355: warning: no description for @param
[ERROR]      * @param factor
[ERROR]        ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/search/Sp.java:147: error: invalid use of @return
[ERROR]      * @return The knowledge being used.
[ERROR]        ^
[ERROR] github/cmu/tetrad/tetrad-lib/src/main/java/edu/cmu/tetrad/search/SvarFges.java:245: error: invalid use of @return
[ERROR]      * @return the true graph.
[ERROR]        ^
[ERROR] 2 errors
[ERROR] 100 warnings
[ERROR] Command line was: /usr/bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in 'github/cmu/tetrad/tetrad-lib/target/apidocs' dir.
[ERROR] 
[ERROR] -> [Help 1]
```

**Comment by jdramsey** [comment]
So two errors and a bunch of Javadoc warnings? By the way I don't know why it's complaining about the <p>'s; that's pretty standard.

I'll look at this tomorrow; I ended up working on the linguistics project all day today and am exhausted :-(

**Comment by kvb2univpitt** [comment]
@jdramsey The GUI component layout is still not properly working in Linux.

Screenshot from 2024-02-01 11-04-52

Should we just skip this?

**Comment by jdramsey** [comment]
I think so. I don't know how to fix it; I tried for several hours. I did
improve it though, in the sense that on Mac and PC it comes up now with all
of the pieces of the layout showing by default. it's only when you try to
maximize it that you get the problem--it doesn't want to resize.

It must have something to do with the Histogram component. Other layouts
resize no problem.

**Comment by jdramsey** [comment]
I can look at that layout again. I just got frustrated with it the
other day. The problem is Swing. In JavaFx, I wouldn't have this problem at
all.

**Comment by jdramsey** [comment]
Actually let me ask you, if you don't try to resize that window for the MC,
does it look OK? On a Mac I'm only having trouble with it if I try to
resize it. Maybe I could just disallow resizing somehow.

**Comment by kvb2univpitt** [comment]
I can try to fix that if you want me to.  I got some time today to do it.

**Comment by jdramsey** [comment]
Oh, sure, if you can figure it out, that would be great! :-D At least if
you could give me another perspective. :-D

I realized just now I'd like to add one small new feature to this release.
There's a way in the interface to do a train/test split of the data, but
there's no way to put the training and testing data you get from that into
separate data boxes. That would be really handy to be able to do right now
with the problem I'm working on, and it's an obvious lacuna in the
interface.

**Comment by kvb2univpitt** [comment]
Everything else looks good.  I'll approve this pull request and then make a branch off the main branch to fix the GUI.

**Comment by jdramsey** [comment]
Nice, thanks! Bryan says he can't find the code he was going to add to the
release, so he's good with releasing.

**Pull request merged**
