### PR TITLE
Fixed bug in Knowledge editor where if if you variable names didn't fit a pre-set variable name spec, drag and drop woudl fail in the editor. Fixed this by turning off the variable name checking.

### PR DESCRIPTION
**Pull request by jdramsey**

### CODE REVIEW

**Comment by jdramsey** [comment]
You can check this by trying to load this file in the editor and making knowledge from it. Try dragging and drop the variables between tiers int eh knowledge editor. This used to fail. Problem is the quotation marks here--they didn't satisfy the name spec. Fixed this by no longer checking the name spec.
[boston-housing.continuous.txt](https://github.com/cmu-phil/tetrad/files/10610275/boston-housing.continuous.txt)

**Comment by jdramsey** [comment]
Issue: https://github.com/cmu-phil/tetrad/issues/1485

**Comment by jdramsey** [comment]
See it works now! In the dev branch currently this can't be done...

Screenshot 2023-02-05 at 12 29 01 AM

**Review by kvb2univpitt — APPROVED** [review]
All tests passed!

**Comment by jdramsey** [comment]
Thanks!

**Pull request merged**
