### PR TITLE
V6.4.0 fix tsimages

### PR DESCRIPTION
**Pull request by kvb2univpitt**
Fix for issue #709

### CODE REVIEW

**Comment by yuanzhou** [comment]
Just tested, and when I chose a different score other than "SEM BIC" or "BDeu", I was supposed to see the error message in 

````
public TsImages(ScoreWrapper score) {
        if (!(score instanceof SemBicScore || score instanceof BdeuScore)) {
            throw new IllegalArgumentException("Only SEM BIC score or BDeu score can be used with this, sorry.");
        }

        this.score = score;
    }
````

But I didn't. And I still saw this popup:

capture

**Comment by kvb2univpitt** [comment]
@yuanzhou The reason why you still see that error is because the logic only accepts either SEM BIC score or BDeu score.  See code below.  Any other score will give you that error message.  What's odd is that BDeu score does not show up in the list of scores.  And, other scores are showing up.

```java
if (score instanceof SemBicScore) {
    ...
} else if (score instanceof BdeuScore) {
    ...
} else {
    throw new IllegalStateException("Sorry, data must either be all continuous or all discrete.");
}
```

@jdramsey Joe, what scores are valid for this algorithm?

**Comment by kvb2univpitt** [comment]
Ahh....I remember now.  Scores are based on data type.  Thus, we see other scores in the list.  Should TsIMaGES take other scores?

**Comment by yuanzhou** [comment]
@jdramsey I think I agree with @kvb2univpitt that this fix should be merged since the purpose of this pull request is to fix the error message. We'll need to fix the underlying bug separately.

**Comment by jdramsey** [comment]
@yuanzhou I have an idea. Why not just change the text? Instead of this:

if (score instanceof SemBicScore) {
    ...
} else if (score instanceof BdeuScore) {
    ...
} else {
    throw new IllegalStateException("Sorry, data must either be all continuous or all discrete.");
}

say this:

if (score instanceof SemBicScore) {
    ...
} else if (score instanceof BdeuScore) {
    ...
} else {
    throw new IllegalStateException("Sorry, the score must be SemBicScore (for the continuous case) or BDeu score (for the discrete case).");
}

**Comment by kvb2univpitt** [comment]
@jdramsey @yuanzhou I think the preferred way would be filter it out in the list of scores.  I'll make this as a separate issue.

clip

**Pull request merged**
