### PR TITLE
Added alternative methods to sample data with custom seed.

### PR DESCRIPTION
**Pull request by kvb2univpitt**
An enhancement for issue #1413.

### CODE REVIEW

**Review by jdramsey — COMMENTED** [review]
In the interface, it seems the bootstrap probabilities now always come out the same--is a seed automatically being used?

**Comment by jdramsey** [comment]
Oh I didn't mean to accept that yet--did we need to add a field in the interface to let the user set the random seed?

**Comment by kvb2univpitt** [comment]
@jdramsey I don't think the original intention was to add a field in the UI to let the user set the random seed for bootstrapping.  If we do that, we will have to make setting seed available for causal-cmd.  I think the idea was just make the method (API) available for programmers to use.

**Comment by jdramsey** [comment]
Got it, then it should be fine. I'll accept it then.

**Comment by kvb2univpitt** [comment]
@jdramsey By the way, if you think we should also make a field for it in the UI, let's make a github issue for it.  I can work on it then.

**Comment by jdramsey** [comment]
@kvb2univpitt I think it would be extremely helpful. If you want help let me know. I'm getting really good at creating new parameters in Tetrad :)

**Comment by kvb2univpitt** [comment]
@jdramsey I also noticed that when you do bootstrapping, the edge properties are missing in the final graph.  I don't think  this was happening before.  OK, you can create a new parameter in Tetrad, and I can fix the missing edge properties.  Now we have two new issues to work on.

```
Resampling Search Result (1):
Graph Nodes:
X4;X14;X7;X15;X8;X1;X20;X17;X10;X3;X11;X5;X12;X2;X16;X6;X18;X19;X13;X9

Graph Edges:
1. X15 --> X20 dd nl
2. X18 --> X19 dd nl
3. X1 o-o X14
4. X10 o-> X19
5. X11 o-> X15
6. X17 o-> X19
7. X18 <-> X16
8. X19 <-> X16
9. X2 o-> X9
10. X3 o-o X17
11. X3 o-> X9
12. X4 o-> X20
13. X7 o-o X11
14. X7 o-o X13
15. X8 o-> X15
16. X8 o-> X18
17. X8 o-o X2
18. X8 o-> X9

Graph Attributes:
BIC: -11261.382599

Graph Node Attributes:
Score: [X4: -479.04548267532056;X14: -739.6183077648645;X7: -180.1371408803079;X15: -768.7695871731235;X8: -650.2210444581827;X1: -1017.6366053367484;X20: -429.06823268965456;X17: -591.3050230158439;X10: -58.26488406072548;X3: -230.4918545355993;X11: -133.48554489895668;X5: -721.4515073907164;X12: -250.92887542792909;X2: -313.8589406664862;X16: -1109.4371764674233;X6: -265.14171452695365;X18: -797.3131332204184;X19: -821.3919738195393;X13: -707.16755857094;X9: -996.6480115148182]


Final Resampling Search Result:
Graph Nodes:
X1;X2;X3;X4;X5;X6;X7;X8;X9;X10;X11;X12;X13;X14;X15;X16;X17;X18;X19;X20

Graph Edges:
1. X1 o-o X14 [X1 o-o X14]:1.0000;
2. X10 o-> X19 [X10 o-> X19]:1.0000;
3. X11 o-> X15 [X11 o-> X15]:1.0000;
4. X15 --> X20 [X15 --> X20]:1.0000;
5. X16 <-> X18 [X16 <-> X18]:1.0000;
6. X16 <-> X19 [X16 <-> X19]:1.0000;
7. X17 o-> X19 [X17 o-> X19]:1.0000;
8. X18 --> X19 [X18 --> X19]:1.0000;
9. X2 o-o X8 [X2 o-o X8]:1.0000;
10. X2 o-> X9 [X2 o-> X9]:1.0000;
11. X3 o-o X17 [X3 o-o X17]:1.0000;
12. X3 o-> X9 [X3 o-> X9]:1.0000;
13. X4 o-> X20 [X4 o-> X20]:1.0000;
14. X7 o-o X11 [X7 o-o X11]:1.0000;
15. X7 o-o X13 [X7 o-o X13]:1.0000;
16. X8 o-> X15 [X8 o-> X15]:1.0000;
17. X8 o-> X18 [X8 o-> X18]:1.0000;
18. X8 o-> X9 [X8 o-> X9]:1.0000;
```

**Comment by jdramsey** [comment]
In which branch should I create the property? I'm thinking of just calling
it "randomSeed".

Joe

**Comment by jdramsey** [comment]
I added a parameter, 'randomSeed' (Params.RANDOM_SEED) in the branch bootstrapRandomSeed. A value of -1 (default)_ means no random seed is set.

**Pull request merged**
