### PR TITLE
fixed issue in graphToLavaan

### PR DESCRIPTION
**Pull request by bja43**
was not correctly printing bi-directed edges.. not it is

### CODE REVIEW

**Comment by jdramsey** [comment]
@bja43 How can I test it?

**Review by jdramsey — APPROVED** [review]
Works! Problem fixed.

**Comment by cg09** [comment]
Who is Lavaan?

**Comment by jdramsey** [comment]
It's a package in R:

https://lavaan.ugent.be/tutorial/

**Pull request merged**
