### PR TITLE
Replaced deprecated method Class.newInstance().

### PR DESCRIPTION
**Pull request by kvb2univpitt**
These changes are necessary for causal-cmd to work with Java 17.

### CODE REVIEW

**Review by jdramsey — APPROVED** [review]
It looks good. Working.

**Comment by jdramsey** [comment]
It's not something I want to do, but if someone else wants to, I won't stop them. We have provided rpy-tetrad, which many people find useful. Anne, who uses R all the time, has no trouble with it.

**Comment by cg09** [comment]
If you have 20 data sets you want to analyze with the same algorithm, you
need to draw a lot of boxes and arrows. In R, you could just list the data
sets.

**Comment by jdramsey** [comment]
We need to talk. You can do that easily in py-tetrad (in Python) or
rpy-tetrad (in R). It's why Bryan prefers to interact with Tetrad from
Python now instead of in the interface.

Send these links to your grandom:

https://github.com/cmu-phil/py-tetrad

https://github.com/cmu-phil/py-tetrad/tree/main/pytetrad/R

Also this paper:

Ramsey, J., & Andrews, B. (2023, November). Py-Tetrad and RPy-Tetrad: A New
Python Interface with R Support for Tetrad Causal Search. In *Causal
Analysis Workshop Series* (pp. 40-51). PMLR.

**Pull request merged**
