### PR TITLE
Fixed duplicate variables problem with time lag graph. Also fixed default directiom problem. Also, removed the graph menu, which didn't apply to time lag graphs.

### PR DESCRIPTION
**Pull request by jdramsey**
https://github.com/cmu-phil/tetrad/issues/1049

### CODE REVIEW

**Comment by jdramsey** [comment]
This is Madelyn's "most egregious  bug" in the interface and is easily fixed. Here is the problem, image below. Notice that if you increase the lags, intermediate variables are duplicated. Also, the orientation of the graph after the increase goes bottom to top instead of top to bottom.

Screen Shot 2019-04-07 at 11 37 46 AM

This is easy to fix--see the changed code in this pull request. The result is as follows.

Screen Shot 2019-04-07 at 11 27 48 AM

Also, the Graph menu wasn't working, and I realized it wasn't applicable to time lag graphs, so I commented it out.

@mglymour @cg09

**Comment by yuanzhou** [comment]
It looks good! I just did some minor UI tweaks:

1. Removed extra separator line
2. Resized the Cancel button so we see the full text

Capture1


Capture

**Comment by jdramsey** [comment]
Thanks!

**Comment by yuanzhou** [comment]
FYI @jdramsey, Jeremy is migrating the nexus repository server from AWS to DBMI VM, that's why the CI test failed for this merge.

**Comment by jdramsey** [comment]
Oh OK. Thanks.

**Pull request merged**
