### PR TITLE
Added support in datareader for loading knowledge groups. In Knowedge2, if x->y is required, it is not counted as forbidden.

### PR DESCRIPTION
**Pull request by jdramsey**

### CODE REVIEW

**Comment by jdramsey** [comment]
Example knowledge file with a forbidden group:

/knowledge
addtemporal

1*  aktinhib b2camp cd3_cd28 g0076 icam2 ly pma psitect u0126
2  akt erk jnk mek p38 pip2 pip3 pka pkc plc raf	

forbiddengroup
aktinhib b2camp cd3_cd28 g0076 icam2 ly pma psitect u0126
akt erk jnk mek p38 pip2 pip3 pka pkc plc raf

requiredirect
g0076 pkc
pma pkc
psitect pip2
u0126 mek
aktinhib akt

Note that the required edges cannot be overridden by the forbidden group, so an adjustment is made to Knowledge2.

**Comment by jdramsey** [comment]
BTW, please check to make sure this is coded OK and that the format is acceptable. If there is a better way to do it, I'm game.

**Comment by jdramsey** [comment]
More details: For the example given, this one:

/knowledge
addtemporal

1* aktinhib b2camp cd3_cd28 g0076 icam2 ly pma psitect u0126
2 akt erk jnk mek p38 pip2 pip3 pka pkc plc raf

forbiddengroup
aktinhib b2camp cd3_cd28 g0076 icam2 ly pma psitect u0126
akt erk jnk mek p38 pip2 pip3 pka pkc plc raf

requiredirect
g0076 pkc
pma pkc
psitect pip2
u0126 mek
aktinhib akt

Note that the required edges cannot be overridden by the forbidden group, so an adjustment is made to Knowledge2.

if you load this knowledge file, you should get a "forbidden group" in the Knowledge interface as indicated. Edges should be forbidden from variables in the first group to variables in the second group. You should be able to include as many forbidden groups as you wish by adding new "forbiddengroup" sections to the Knowledge file.

If you change "forbiddengroup" to "requiredgroup", the pair of rows should load as a required group in the interface. Edges should be required from variables in the first group to variables in the second group. You should be able to add as many required groups as you like by adding new "requiredgroup" sections in the Knowledge file.

You should be able to add any mix of forbidden and required groups by adding the indicated "forbiddengroup" sections and "requiredgrup" sections fo the Knowledge file.

It should not matter what order the sections of the knowledge file come in, but there should only be one "addtemporall" section.

The forbidden and required groups interface is broken currently, but that's another issue. You should be able to add any combination of variables from the list of variables at the top of the interface to any forbidden or required group, but that gets messed up. 

Also, it would be good if you could load knowledge from a file without having to specify the variables first (by adding an edge from a dataset, e.g.). Something is preventing this. Probably some dumb thing I did.

**Comment by espinoj** [comment]
Gonna merge. Will move functions to non deprecated data reader. Should work fine with upcoming new knowledge file format

**Pull request merged**
