### PR TITLE
Final release version.

### PR DESCRIPTION
**Pull request by jdramsey**
1. Fixing condition for formatting search graphs using knowledge tiers.
2. Added parameter to SemBic Score and Ebic.Score to allow covariance matrix to not be precomputed.
3. Improved parallelization for FGES.
4. Fixed some bugs in the bootstrapping code and changed bootstrapping type to 1, 2, 3 (was 0, 1, 2).
5. Fixed parallelization for bootstrapping code.
6. Fixed all scores so that they return NaN if the score can’t be calculated.
7. Fixed it so that if you close all sessions, a new one automatically appears.
8. Switched to common pool for parallelizing throughout code.
9. Fixed Javadoc errors (not warnings) so that Javadoecs now build. 
10. Added maven-javadoc-plugin to Maven pom.xml so that javadocs will be attached to release.
11. Added plugin maven-source-plugin to Maven pom.xml so that sources will be attached to release.
12. Setting max indegree, outdegree, and degree to -1 (unlimited).
13. Removed the model p-value from the Bayes estimator, as it uses a calculation of the null which for even moderately sized models can hang.

### CODE REVIEW

**Comment by kvb2univpitt** [comment]
@jdramsey I've got a unit test failure:

```
Running edu.cmu.tetrad.test.TestCellProbabilities
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec <<< FAILURE!
testCreateUsingBayesIm(edu.cmu.tetrad.test.TestCellProbabilities)  Time elapsed: 0.003 sec  <<< FAILURE!
junit.framework.AssertionFailedError: expected:<0.02> but was:<0.1118280623757343>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:120)
	at junit.framework.Assert.assertEquals(Assert.java:129)
	at junit.framework.TestCase.assertEquals(TestCase.java:277)
	at edu.cmu.tetrad.test.TestCellProbabilities.testCreateUsingBayesIm(TestCellProbabilities.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

I also got a lot of ***This class does not have the expected 'serializableInstance' method***:

```
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.search.Cstar$Record
..........................................50
........
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.bayes.JunctionTreeAlgorithm$TreeSeparator
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.bayes.JunctionTreeAlgorithm
..............
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.bayes.JunctionTreeUpdater
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.bayes.JunctionTreeAlgorithm$TreeNode
....
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.TimeoutComparison$SimulationWrapper
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.Comparison$AlgorithmSimulationWrapper
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.TimeoutComparison$AlgorithmSimulationWrapper
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.Comparison$AlgorithmWrapper
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.TimeoutComparison$AlgorithmWrapper
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.score.MagSemBicScore
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.score.BdeuScore
..
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.score.ConditionalGaussianBicScore
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.score.SemBicScoreDeterministic
...
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.score.EbicScore
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.score.FisherZScore
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.score.DiscreteBicScore
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.score.DSeparationScore
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.score.SemBicScore
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.score.CciScore
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.score.DegenerateGaussianBicScore
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.score.PositiveCorrScore
..
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.multi.FasLofs
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.multi.FaskVote
100
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.multi.FasLofsConcatenated
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.multi.ImagesBDeu
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.multi.FgesConcatenated
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.multi.CcdMaxConcatenated
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.multi.FASK
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.multi.ImagesSemBic
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.multi.MultiFaskV1
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.multi.PcStableMaxConcatenated
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.multi.FaskConcatenated
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.multi.ImagesPcStableMax
...
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.FirstInflection
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.oracle.pattern.CStaR
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.oracle.pag.SvarFci
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.oracle.pag.FciMax
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.oracle.pag.SvarGfci
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.oracle.pag.RfciBsc
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.oracle.pag.CCD
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.oracle.pag.Cfci
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.oracle.pag.CcdMax
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.oracle.pag.GRaSPFCI
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.oracle.pag.Gfci
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.oracle.pag.Fci
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.oracle.pag.Rfci
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.oracle.cpdag.GesMe
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.oracle.cpdag.SP
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.oracle.cpdag.SingleGraphAlg
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.oracle.cpdag.PcAll
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.oracle.cpdag.Pcd
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.oracle.cpdag.FgesMeasurement
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.oracle.cpdag.MBFS
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.oracle.cpdag.Fges
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.oracle.cpdag.CPC
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.oracle.cpdag.CpcStable
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.oracle.cpdag.GRaSP
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.oracle.cpdag.PCMAX
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.oracle.cpdag.FgesMb
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.oracle.cpdag.PC
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.oracle.cpdag.GRaSP_Orig
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.oracle.cpdag.PcStable
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.oracle.cpdag.FAS
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.StabilitySelection
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.external.ExternalAlgorithmBnlearnMmhc
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.external.ExternalAlgorithmPcalgGes
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.external.ExternalAlgorithmPcalgPc
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.external.ExternalAlgorithmTetrad
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.external.ExternalAlgorithmIntersection
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.external.ExternalAlgorithmBNTPc
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.cluster.Ftfc
150
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.cluster.Fofc
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.cluster.Bpc
..
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.mixed.cpdag.MixedFgesDiscretingContinuousVariables
..
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.StARS
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.pairwise.EB
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.pairwise.RSkewE
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.pairwise.Tanh
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.pairwise.RSkew
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.pairwise.Skew
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.pairwise.R3
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.pairwise.FaskPW
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.pairwise.R1
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.pairwise.R2
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.algorithm.pairwise.SkewE
...
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.Comparison$SimulationWrapper
.....
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.independence.PositiveCorr
....
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.independence.DSeparationTest
...............
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.graph.SingleGraph
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.simulation.SemSimulation
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.simulation.BayesNetSimulation
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.simulation.StandardizedSemSimulation
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.simulation.LinearFisherModel
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.simulation.GeneralSemSimulationSpecial1
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.simulation.ConditionalGaussianSimulation
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.simulation.TimeSeriesSemSimulation
200
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.simulation.LinearSineSimulation
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.simulation.GeneralSemSimulation
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.simulation.BooleanGlassSimulation
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.simulation.LeeHastieSimulation
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.algcomparison.simulation.SemThenDiscretize
.............................................250
..............
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.data.simulation.LoadDataAndGraphs
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.data.simulation.LoadDataFromFileWithoutGraph
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.data.simulation.LoadContinuousDataAndGraphs
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.data.simulation.LoadContinuousDataAndSingleGraph
.
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.data.simulation.LoadContinuousDataSmithSim
................................300
..................................................350
..................................................400
......................
This class does not have the expected 'serializableInstance' method: class edu.cmu.tetrad.graph.EdgeTypeProbability
```

Did you change something to cause this?  I've never seen this before.

**Comment by jdramsey** [comment]
Thanks--I'll work on these. I did change something; I'll see if I can't just fix the problems. BTW I realized I'm not ready yet to release yet anyway. I still need to sign the jars.

**Comment by jdramsey** [comment]
I commented out that print statement that was generating all of those prints and I think I've fixed the failure in that one test. Also a few more fixes:

1. Fixed error message if user tries to estimate a time lagged dataset using non-time-lagged data to recommend that they convert the data to time lagged data using the data box first.
2. Made a more descriptive error message for when MimBuild fails due to estimation degrees of freedom being too low.
3. Adding an informative error message if the user tries to create a standardized SEM IM, which is currently incoherent.
4. Fixed it so that knowledge for a Time Lag Graph can be retried from it by attaching a Knowledge box.
5. Fixed is to that if a d-separation test or score is used as input to a search algorithm, and the source graph has knowledge tiers defined in the variables, and knowledge is not otherwise defined, the tiered knowledge is used.
6. Fixed it so that if an algorithm that takes both a test and a score is run from d-separation, the graph is set for both the test and the score.
7. Fixed bug where if a SEM IM was created with non-Gaussian errors through the Graph->PM->IM->Simulation route, variables would still be simulated as Normal even if non-Gaussian errors were specified.
8. For MiBuild, switched pattern algorithm to GRaSP.
9. Made a better error message for the case where the user tries to create a standardized SEM IM with a time lag model with latent variables.
10. Changed method of randomly initializing rows in a Bayes IM conditional probability table (CPT) to use the Beta(alpha, beta) distribution to pick values, where beta = # columns and alpha = beta / 4.0.

**Comment by cg09** [comment]
How can GRASP do a pattern search on latent variables?

**Comment by jdramsey** [comment]
You'll have to do a PAG search of course. We've included in the upcoming build an algorithm called GRaSP-FCI which wraps GRaSP in the same way as GFCI wraps FGES.

You could also use SP (Raskutti and Uhler's "Sparest Permutation" algorithm that necessarily finds a frugal DAG) very productively for small models of up to about 8 or 9 variables, and there's a PAG algorithm wrapper for that as well called SP-FCI that wraps SP in the same way that GFCI wraps FGES.

**Comment by jdramsey** [comment]
List of all issues for this list has been moved to:

https://github.com/cmu-phil/tetrad/wiki/Issues-for-forthcoming-version-7-1-0

**Comment by cg09** [comment]
But MImbuild doesn't work. Sigh.

**Review by kvb2univpitt — APPROVED** [review]
Everything seems to work after the TestCellProbabilities was disabled.

**Comment by jdramsey** [comment]
Thanks!

**Comment by cg09** [comment]
Not even close to what MIMbuild is supposed to do. Can we use EM to
estimate the values for latent variables and apply GRASP to that inferred
data?

**Pull request merged**
