### PR TITLE
V6.8.0 jta extended

### PR DESCRIPTION
**Pull request by kvb2univpitt**
Added a method to the junction tree to find the joint probability of nodes given their parents.
For an example: given x <-- z --> y, we can now find P(x,y|z).
Another example: given x <-- z --> y <-- w, we can now find P(x,y|z,w).

### CODE REVIEW

**Comment by kvb2univpitt** [comment]
Here's how to test it.  Here's a zip containing a dataset and a graph [data_graph.zip](https://github.com/cmu-phil/tetrad/files/5236249/data_graph.zip) that has the following probabilities:

```
Node: x
	x=0	x=1
z=0	0.6204	0.3796
z=1	0.2953	0.7047

Node: z
z=0	z=1
0.1903	0.8097

Node: y
		y=0	y=1
z=0	w=0	0.3967	0.6033
z=0	w=1	0.2750	0.7250
z=1	w=0	0.1964	0.8036
z=1	w=1	0.4713	0.5287

Node: w
w=0	w=1
0.4491	0.5509
```
You can compute P(x=0,y=0|z=0,w=0) = 0.6204 * 0.3967 = 0.24611268 and compare it against the junction tree.

The **edu.cmu.tetrad.bayes.JunctionTreeAlgorithmTest** has the method public void t**estJointProbGivenParents()** that has all the code set up for this testing.  Just run it with different values and compare it with your calculation from the above table.

**Comment by espinoj** [comment]
Hmmm.  Having Junction Tree means we could bring back the classify button.  @jdramsey

**Comment by jdramsey** [comment]
@espinoj We could!

@kvb2univpitt I have a meeting in a couple of minutes but I'll load this up and test it afterward as per instruction...

**Comment by jdramsey** [comment]
@kvb2univpitt OK I'll try this now. Give me a few.

**Review by jdramsey — APPROVED** [review]
It works!

**Pull request merged**
