### PR TITLE
Several fixes, updates.

### PR DESCRIPTION
**Pull request by jdramsey**
Several fixes--see commits. Will make a list.

### CODE REVIEW

**Comment by jdramsey** [comment]
These fixes:

https://github.com/cmu-phil/tetrad/wiki/Forthcoming-fixes

**Comment by bja43** [comment]
deleting required edges appears to be bugged, they reappear after deleting them if you check/uncheck some of the checkboxes

**Comment by jdramsey** [comment]
@bja43 Can you try it now?

**Comment by bja43** [comment]
The show forbidden by tiers checkbox does not appear to do anything. I put in some tiered knowledge (including forbid within tier knowledge) after which checking the box in question did not do anything. Also, I was able add an explicitly required edge that conflicted with the tiered knowledge that I specified without any sort of error being thrown.

**Comment by bja43** [comment]
It also looks like you can require edges that form a two-cycle (not sure if this should be allowed since some Tetrad algorithm can indeed learn two cycles.) 

I am also seeing the same issues that I mentioned earlier for tiers, but for knowledge groups.

**Pull request merged**
