### PR TITLE
A few more fixes for 7.6.4 release. 

### PR DESCRIPTION
**Pull request by jdramsey**
* Added a menu to the interface to let the user check whether their graph is of a certain graph type (DAG, CPDAG, MPDAG, MAG, PAG).

* Added parsers/renderers in the interface for the amat.cpdag and amat.pag graph matrix types used in PCALG.

* Adjusted the m-separation algorithm so that it can correctly infer d-separation facts from CPDAGs without first taking a DAG in the CPDAG.

* Added a link from a graph-containing box to Algcomparison in the UI to let the user specify a specific graph for the comparison.

### CODE REVIEW

**Comment by bja43** [comment]
The check legal MPDAG disagrees with the check legal CPDAG for a DAG without knowledge (which should not happen). Additionally, It is unclear how to give the check to knowledge when checking for legal MPDAG.

Please provide PCALG amat files for testing, I do not know what this format is.

Are there unit tests for checking if m-separation is working correctly?

User-specified graphs appear to be working great.

**Comment by jdramsey** [comment]
Some work got lost; there should have been a "Meek rules" submenu in the Graph box Graph menu. I've re-added that.

**Comment by jdramsey** [comment]
Also, let me add an item to highlight all edges in cycles. That seems useful.

**Comment by jdramsey** [comment]
The Graph menus are now the way I intended, with the Meek Rules submenu. I don't know how those changes got lost, but they're back now.

I may need to zoom in with you to see where CPDAG and MPDAG (where it's actually a CPDAG) disagree.

I'll add a test for m-separation in the context of a PAG model.

**Comment by jdramsey** [comment]
You know, in addition to the Meek rules, I could add an item for final FCI rules, in case someone wants to add orientations to a PAG. No need to be stingy; these things are easy to add. (I can also easily take it away if you don't like it.)

**Comment by jdramsey** [comment]
Hmmm.... is there such a graph type as MPAG, a correlate of MPAG, where you test whether a graph would be a PAG if you applied the DAG to PAG operator (I think)? I.e., if it's a PAG where additional knowledge has been applied and the final FCI rules applied? I'll try it out and see if we can add it sensibly...

Also, I may need to distinguish Spirtes from Zhang's final rules, but it is easy enough... give me half an hour...

**Comment by jdramsey** [comment]
A few more adjustments.
* Added some graph manipulation options to the Graph box's Graph menu.
    * Some more graph type checks.
        * DAG, CPDAG, MPDAG, PAG, MAG, MPAG (a novel type that may not survive review)
    * Some more highlight edges checks.
        * Undirected edges
        * Edges in cycles
    * Some undo options.
        * Undo graph change, control-Z
        * Revert to the original graph in the box, control-O
        * Revert to CPDAG, control-R
        * Revert to PAG, control-P
    * Some apply final rules options 
        * Apply Meek rules, control-M
        * Apply FCI final rules, control-F
  * Added a test for m-separation, as follows:
```
        /**
         * A test of m-connection. We generate 10 random graphs with latents and check that dagToPag
         * produces a legal PAG. We then call dagToPag again on the PAG and check that the result is
         * also a legal PAG.
         */
        @Test
        public void test12() {
            for (int i = 0; i < 10; i++) {
                Graph graph = RandomGraph.randomGraph(10, 3, 10,
                        10, 10, 10, false);
                Graph pag = GraphTransforms.dagToPag(graph);
                assertTrue(pag.paths().isLegalPag());
                Graph pag2 = GraphTransforms.dagToPag(pag);
                assertTrue(pag2.paths().isLegalPag());
            }
        }
```

**Comment by jdramsey** [comment]
Here are the specs for amat.cpdag and amat.pag. I'll try to figure out a way to put these in the Tetrad documentation somewhere.
```
Coding for type amat.cpdag:

0:
No edge or tail

1:
Arrowhead

Note that the edgemark-code refers to the row index (as opposed adjacency matrices of type mag or pag). E.g.:

    amat[a,b] = 0  and  amat[b,a] = 1   implies a --> b.
    amat[a,b] = 1  and  amat[b,a] = 0   implies a <-- b.
    amat[a,b] = 0  and  amat[b,a] = 0   implies a     b.
    amat[a,b] = 1  and  amat[b,a] = 1   implies a --- b.
Coding for type amat.pag:

0:
No edge

1:
Circle

2:
Arrowhead

3:
Tail

Note that the edgemark-code refers to the column index (as opposed adjacency matrices of type dag or cpdag). E.g.:

  amat[a,b] = 2  and  amat[b,a] = 3   implies   a --> b.
  amat[a,b] = 3  and  amat[b,a] = 2   implies   a <-- b.
  amat[a,b] = 2  and  amat[b,a] = 2   implies   a <-> b.
  amat[a,b] = 1  and  amat[b,a] = 3   implies   a --o b.
  amat[a,b] = 0  and  amat[b,a] = 0   implies   a     b.
```

**Comment by jdramsey** [comment]
I see the issue with amat.cpdag I think--the file name for it was wrong. Fixed.

**Comment by jdramsey** [comment]
Also I went through and fixed the javadocs up again.

**Comment by jdramsey** [comment]
OK, I think this is ready to review except for this item, which I don't know how to fix:
```
The check legal MPDAG disagrees with the check legal CPDAG for a DAG without knowledge (which should not happen). Additionally, It is unclear how to give the check to knowledge when checking for legal MPDAG.
```

**Comment by jdramsey** [comment]
I realized that SEM models won't undo correctly, so I turned off graph undo for those.

**Comment by jdramsey** [comment]
Oh, what the heck--I should try to do redo as well for graph changes.  Trying to think how...

**Comment by jdramsey** [comment]
Took the MPAG type out of the interface since it's not a defined graph type in the literature. (If someone wants to define it in the literature, please do and send me the link.)

**Comment by jdramsey** [comment]
OK, I think (once again) this can be reviewed with the above adjustments. @bja43

**Comment by jdramsey** [comment]
Well, OK, I also added a control-X cut item to the graph menu. People have always complained about not knowing how to delete stuff from a graph in a graph box. Pressing the delete key was not obvious in testing. May as well fix it; why not?

**Comment by jdramsey** [comment]
Also added a long-requested menu item to show PAG edge and coloring type information.

**Comment by jdramsey** [comment]
OK I think this is ready.

**Comment by jdramsey** [comment]
I added a new experimental algorithm, which is now called LV-Lite. This is an entirely score-based variate of FCI/BFCI.

**Comment by jdramsey** [comment]
Bryan says I can merge this. :)

**Pull request merged**
