### PR TITLE
V6.7.0 multiple graph display

### PR DESCRIPTION
**Pull request by kvb2univpitt**
A fix for issue #991.

### CODE REVIEW

**Comment by yuanzhou** [comment]
Just tested and it looks good in the search resulting graph panel. But when I attached a graph box to the search box, I only see the first one graph instead of all graphs. Prob an easy fix in the graph editor. Thanks!

**Comment by kvb2univpitt** [comment]
Oh I see.   The problem is in two places.  Fixing it now.  Good catch!

**Comment by kvb2univpitt** [comment]
@yuanzhou It looks like in the previous Tetrad multiple graphs were also not shown in the graph box.  From looking at the code, the GraphEditor is meant to handle only one graph.  Let's wait and see what @jdramsey says about making the GraphEditor showing multiple graph.  This will be a new issue since we are adding new feature not bug fixing.

**Comment by yuanzhou** [comment]
I agree with @kvb2univpitt. Currently it seems the graph box is being used for two purposes:

1. Create a graph box and make new graph, then use the graph with PM, IM and do a search using the graph as input.

2. Connect a graph box to a search box to make changes to the search resulting graphs. This is where the issue comes from. 

We first need to clearly define the role of this graph box and how to use it correctly.

**Pull request merged**
