### PR TITLE
Move undirected edge column next to directed edge column.

### PR DESCRIPTION
**Pull request by kvb2univpitt**
A fix for issue #1411.

### CODE REVIEW

**Comment by jdramsey** [comment]
The table looks wonderful! It's just that the green columns are never used. I'm wondering if the PAG coloring is being applied to the individual PAGs.

Also, the display of the PAG coloring changed (Peter signed off on this). We need to quickly verify which properties are being displayed here. I think the thick green ones should be "visible"--i.e., the property should be NL. These come out as thick blue edges in the display, so maybe that can be made blue? I'm not sure what the thin green ones are. Are these possible latent (property PL)?

**Comment by jdramsey** [comment]
That reminds me, I need to add a menu item for the Graph box to apply or unapply the PAG coloring. I mean to do that. Id you copy a search PAG into another box it loses the PAG coloring and you can't get it back. I'll add this as an issue and assign it to myself to do after yours are all merged.

**Comment by kvb2univpitt** [comment]
Yes, the non-bold green (thin) ones are *possible latent*.  Here's the coloring scheme:

| Edge Type | Edge Property | Display    |
|-----------|---------------|------------|
| <--       | none          | black      |
| -->       | none          | black      |
| <--       | pd,nl         | green      |
| -->       | pd,nl         | green      |
| <--       | dd,nl         | green,bold |
| -->       | dd,nl         | green,bold |

**Comment by kvb2univpitt** [comment]
>  I think the thick green ones should be "visible"--i.e., the property should be NL. These come out as thick blue edges in the display, so maybe that can be made blue?

@jdramsey Can we deal with this as a separate issue?  This issue is about moving the *undirected* column of the table to a different location.

**Comment by jdramsey** [comment]
Yes of course!

**Comment by jdramsey** [comment]
Sorry I got pulled into another meeting that's turned out to last a long
time...

**Pull request merged**
