### PR TITLE
Nl sim mxnt dlingam

### PR DESCRIPTION
**Pull request by bja43**
Added Direct LiNGAM

### CODE REVIEW

**Comment by cg09** [comment]
How does direct LingAm work with Knowledge... as with other algorithms?

**Comment by bja43** [comment]
The current implementation does not allow for background knowledge, however it could be modified to account for some forms of background knowledge. Required edges might be a bit tricky, but I don't see any issue with adding functionality for tiers or forbidden edges.

**Review by jdramsey — APPROVED** [review]
Awesome!!! :-D

**Comment by cg09** [comment]
Here is how knowledge was implemented in a github version.

**Comment by jdramsey** [comment]
Here's how it was implemented in the Lingam Python package:

https://lingam.readthedocs.io/en/latest/tutorial/pk_direct.html

**Pull request merged**
