### PR TITLE
Updated the bootstrapping API.

### PR DESCRIPTION
**Pull request by jdramsey**
This replaces the old bootstrapping API.

Updates to the ICA algorithms, ICA-LiNGAM and ICA-LiNG-D, are included here for completeness.

More documentation updates need to bedone still.

### CODE REVIEW

**Comment by jdramsey** [comment]
All JavaDoc warnings have been fixed.

I thoroughly tested the algorithms; so far as I can tell, all algorithms are now performing as expected. I tested algorithms on linear Gaussian, linear non-Gaussian, discrete, and mixed data. I also tested lagged data for the SVAR algorithms and pairwise algorithms. I tested CSTaR and MGM, the problem cases from before. I did see a few small issues, which I fixed. All algorithms perform correctly without bootstrapping and display error messages to help the user understand what may go wrong. I adjusted the texts of several error messages to be more helpful to the user.

I then tested bootstrapping using the new bootstrapping API. Certain algorithms were unsuitable for bootstrapping, so for those I didn't extend AbstractBootstrappingAlgorithm. I adjusted the interface so that algorithms that do not do bootstrapping (including, for now, the multi-dataset algorithms) say so in the interface. I tried varying the bootstrapping parameters successfully. I check to make sure the ensemble display options work. I checked to make sure the Edges tab was updating correctly for bootstrapping with sensible edge statistics.

**Comment by jdramsey** [comment]
Algorithm updates for this branch include:

- ICA-LiNGAM
- ICA-LiNG-D
- DirectLingam

**Comment by jdramsey** [comment]
These changes are in response to a replacement (by Kevin) of the bootstrapping API in Tetrad.

**Review by kvb2univpitt — APPROVED** [review]
Looks like bootstrap is working as expected.  However, there were other non-related issues that popped up during testing.  We will create a separate issue on github to fix them.

**Pull request merged**
