### PR TITLE
Changes toward 7.6.2 release.

### PR DESCRIPTION
**Pull request by jdramsey**
See:

https://github.com/cmu-phil/tetrad/wiki/Forthcoming-fixes

### CODE REVIEW

**Comment by yasu-sh** [comment]
@jdramsey you requested me on this revew. I need to know what should I check or not. 
Just approving is possible, but I don't think it is appropriate. Let me have some additional information. (how much/how many)

**Review by kvb2univpitt — APPROVED** [review]
Couple bugs were found but we had a discussion about it already.

**Comment by jdramsey** [comment]
@yasu-sh Kevin approved it but gave me "homework."--there are some issues he'd still like to be fixed. So, if you also have issues you'd like to be fixed, let me know, and I'll work on them. Thanks :-) I'm going to work on it over the weekend.

Kevin tested the Processing... dialog issue I fixed for you, and it worked on his Linux machine, so I think that's good now.

There was a difficult problem he brought up--on his machine, at least when you click stop for the processing button, the underlying threads don't stop. That obviously has to be fixed, but I don't think it needs to be fixed for the next release.

**Comment by jdramsey** [comment]
@yasu-sh Anyway, all of that work is now in the development branch, so any other work I do will be in a new branch.

**Comment by yasu-sh** [comment]
> @yasu-sh Kevin approved it but gave me "homework."--there are some issues he'd still like to be fixed. So, if you also have issues you'd like to be fixed, let me know, and I'll work on them. Thanks :-) I'm going to work on it over the weekend.

I understand the situation and I am afriad I did not check your mentions during the weekend.
I'll get back to you if I find any topics.

**Pull request merged**
