### PR TITLE
Added links so you can draw an edge from Time Lag Data to Knowledge and it will form the time lag knowledge. Still, this knowledge should be passed automatically to the search if available.

### PR DESCRIPTION
**Pull request by jdramsey**
Added Time Lag Data --> Knowledge connection.

### CODE REVIEW

**Comment by jdramsey** [comment]
@espinoj I added a few lines of code so that if you have a Time Lag Graph and you attach a Knowledge box you get the time lag knowledge (future doesn't cause the past).

We used to have it so that this knowledge was passed to the search automatically in the Generalized Algorithm Editor, but it stopped doing this.

**Comment by espinoj** [comment]
Can I please get a tet file to see how to use this?

**Comment by jdramsey** [comment]
Sure, I will make one and send it by email.

**Comment by jdramsey** [comment]
Example:

[timelagsearchexample.tet.zip](https://github.com/cmu-phil/tetrad/files/1674639/timelagsearchexample.tet.zip)

**Comment by espinoj** [comment]
Thanks. I get it.  I thought there was some new knowledge function that automatically made the tiers.

**Comment by jdramsey** [comment]
Oh, the tiers are being made automatically. It's still a little buggy. To get them, you need to make a new Knowledge box off of TimeLagData, and then they will be made. If you destroy and recreate the knowledge they disappear.

**Pull request merged**
