### PR TITLE
Fixing issue with display of 2-factor random MIM graphs.

### PR DESCRIPTION
**Pull request by jdramsey**
See issue https://github.com/cmu-phil/tetrad/issues/1725.

### CODE REVIEW

**Comment by jdramsey** [comment]
@yasu-sh Could you check to make sure this fixes the issue you reported on your machine?

**Comment by kvb2univpitt** [comment]
@jdramsey I was able to compile and run tetrad-gui.  Looks like the documentations for the algorithms, tests of independence, and scores are back.

**Comment by kvb2univpitt** [comment]
Just tested the 2-factor random MIM bug.  Seems to be working.

**Comment by kvb2univpitt** [comment]
Should I wait until @yasu-sh test it on his computer before approving it?

**Comment by jdramsey** [comment]
Pulled this code into fix_docs_2024_2_6, so closing this PR.

**Comment by jdramsey** [comment]
No I think it's OK.

**Comment by jdramsey** [comment]
If you approve it I'll make the release.

**Comment by kvb2univpitt** [comment]
I didn't approve or merge it yet.

**Comment by jdramsey** [comment]
OK.

**Comment by jdramsey** [comment]
Sorry I must have clicked the wrong button.

**Review by kvb2univpitt — APPROVED** [review]
Seems to be working as expected.

**Comment by kvb2univpitt** [comment]
Ok.  Approved and merged!

**Comment by jdramsey** [comment]
Thanks!!! :-D :-D :-D

**Comment by yasu-sh** [comment]
@jdramsey @kvb2univpitt Excellent! Thank you for quick action.

**Pull request merged**
