### PR TITLE
experimental - renaming FGS to FGES throughout the code.

### PR DESCRIPTION
**Pull request by jdramsey**

### CODE REVIEW

**Comment by jdramsey** [comment]
I renamed the FGS classes to FGES, and renamed all such fields, file names, help files, and relevant comments. Tests pass for me.

**Comment by espinoj** [comment]
please delay merging this until I can tag and build out to the maven repository

**Comment by jdramsey** [comment]
No problem. I am expert at delaying.

**Comment by espinoj** [comment]
All, tetrad before method name changes is tagged tetrad-6.1.0 and is currently also in master.

**Pull request merged**
