### PR TITLE
Kevin bs seed

### PR DESCRIPTION
**Pull request by kvb2univpitt**
Added seed to bootstrap parameter.  This is an extension for issue ##1413

### CODE REVIEW

**Comment by jdramsey** [comment]
This looks really good! For some reason all of the results are coming out better than I'm used to.

**Comment by jdramsey** [comment]
I'll take it!

**Comment by jdramsey** [comment]
OK if I try PC (which I *know* is non-random in every way) successive runs with the same seed yield the same bootstrap probability edge results. Good! So now I take if that the algorithms that don't do that have random elements--I'll have to track those down.

**Comment by kvb2univpitt** [comment]
@jdramsey Please hold off on merging.  I found a bug.  I need to move the random number generator outside of the loop.

**Comment by kvb2univpitt** [comment]
@jdramsey OK.  I fixed it!  The random number generator needs to be created outside of the for-loop or else a new random number generator will be created every iteration of the loop.  Please try it now.  Thanks!

**Comment by jdramsey** [comment]
Oh--is this a bug too? If I set the seed to -1, different runs should come out different but they're all the same...

**Comment by kvb2univpitt** [comment]
@jdramsey I don't think so.  The default (-1) will use the current random number generator **RandomUtil.getInstance()**.  If the seed is > 0, we will use the follow:

```java
RandomGenerator randomGenerator = new SynchronizedRandomGenerator(new Well44497b(seed));
```

Basically, it's the same random number generator but with different seed.

**Review by jdramsey — APPROVED** [review]
Great!!

**Pull request merged**
