### PR TITLE
Disabling remote job execution to allow Tetrad GUI to launch properly.

### PR DESCRIPTION
**Pull request by jdramsey**
This can easily be reversed.

### CODE REVIEW

**Comment by kvb2univpitt** [comment]
@jdramsey Commenting out the code will solve the issue you're having, but it will not make Tetrad independent.  Tetrad is still depending on the libraries hosted at Pitt.  I can remove those libraries and clean up the code.  Hopefully, it will go smoothly.

**Comment by jdramsey** [comment]
Thanks! Can you do this on your end or should I try?

**Comment by kvb2univpitt** [comment]
I can do it on my end.  Should I create a new branch off of the development branch or should I just make changes to your ***6.9.0-hotfix*** branch?

**Comment by jdramsey** [comment]
I'm happy to let you make all the changes--it may be more coherent that way. We can close this one.

**Comment by cg09** [comment]
Yes, but where should Kevin do it?

**Comment by jdramsey** [comment]
@cg09 In a new pull request...

**Comment by kvb2univpitt** [comment]
Ok.  I'll make a new branch then.

**Comment by kvb2univpitt** [comment]
@jdramsey @cg09 I have cleaned up the code.  All of the BD2K related code and libraries have been completely removed.  Please see pull request #1363.

**Comment by cg09** [comment]
Kevin,  Thanks.

**Comment by kvb2univpitt** [comment]
@cg09 You're welcome.  :)

**Comment by jdramsey** [comment]
@cg09 @kvb2univpitt Every all seems to still work. Thanks for all the effort, which was substantial. I'll do the review.

**Comment by kvb2univpitt** [comment]
@jdramsey I think we can close this now?

**Comment by jdramsey** [comment]
Yes, thanks!

**Pull request closed without merging**
